- name: JQ is present
  apt:
    name: jq
    force: yes
  tags: [common]

- name: Host is present
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.host_ip }}"
    line: "{{ item.host_ip }} {{ item.host_name }}"
  with_items: hosts
  tags: [common]

- name: Services are not running
  service:
    name: "{{ item }}"
    state: stopped
  ignore_errors: yes
  with_items: obsolete_services
  tags: [common]

- name: Debian add fish
  apt_repository:
    repo: ppa:fish-shell/release-2
    update_cache: yes
    state: present
  tags: [common, fish]

- name: Fish is present
  apt:
    name: fish
    state: latest
    force: yes
  tags: [common, fish]

- name: make fish default
  user:
    name: vagrant
    shell: /usr/bin/fish
  sudo: yes
  tags: [common, fish]

- name: htop is present
  apt:
    name: htop
    state: latest
    force: yes
  tags: [common, htop]
  
